---
dynamodb_table: UserDataSwap
sqs_queue: user-data-swap-restart-delay
active_mode: False
restart_delay: 0
user_data: |-
  #cloud-config

  bootcmd:
    - echo HELLO FROM USER DATA SCRIPT | tee /msg > /dev/kmsg
    - poweroff
